trainingInput:
  scaleTier: BASIC_GPU
  runtimeVersion: '1.13'
  hyperparameters:
    goal: MAXIMIZE
    hyperparameterMetricTag: epoch_val_ssim
    maxTrials: 1000
    maxParallelTrials: 10
    enableTrialEarlyStopping: TRUE
    params:
    - parameterName: lg_c
      type: DISCRETE
      discreteValues:
      - False
      - True
    - parameterName: res
      type: DISCRETE
      discreteValues:
      - False
      - True
    - parameterName: actv
      type: CATEGORICAL
      categoricalValues:
      - relu
      - selu
    - parameterName: f_h
      type: INTEGER
      minValue: 3
      maxValue: 9
      scaleType: UNIT_LINEAR_SCALE
    - parameterName: f_w
      type: INTEGER
      minValue: 3
      maxValue: 9
      scaleType: UNIT_LINEAR_SCALE
    - parameterName: f1
      type: INTEGER
      minValue: 8
      maxValue: 64
      scaleType: UNIT_LINEAR_SCALE
    - parameterName: f2
      type: INTEGER
      minValue: 8
      maxValue: 128
      scaleType: UNIT_LINEAR_SCALE
    - parameterName: f3
      type: INTEGER
      minValue: 8
      maxValue: 256
      scaleType: UNIT_LINEAR_SCALE
    - parameterName: f4
      type: INTEGER
      minValue: 8
      maxValue: 512
      scaleType: UNIT_LINEAR_SCALE
    - parameterName: fbn
      type: INTEGER
      minValue: 8
      maxValue: 1024
      scaleType: UNIT_LINEAR_SCALE
    - parameterName: lr
      type: DOUBLE
      minValue: 0.00001
      maxValue: 0.01
      scaleType: UNIT_REVERSE_LOG_SCALE
    - parameterName: l_ssim
      type: DOUBLE
      minValue: 0
      maxValue: 1
      scaleType: UNIT_LINEAR_SCALE
    - parameterName: l_mae
      type: DOUBLE
      minValue: 0
      maxValue: 1
      scaleType: UNIT_LINEAR_SCALE
    - parameterName: l_mse
      type: DOUBLE
      minValue: 0
      maxValue: 1
      scaleType: UNIT_LINEAR_SCALE
