trainingInput:
  scaleTier: BASIC_GPU
  runtimeVersion: '1.13'
  hyperparameters:
    goal: MAXIMIZE
    hyperparameterMetricTag: epoch_val_ssim
    maxTrials: 50
    maxParallelTrials: 1
    maxFailedTrials: 100
    enableTrialEarlyStopping: TRUE
    params:
    - parameterName: m
      type: DISCRETE
      discreteValues:
      - 0
    - parameterName: lg_c
      type: DISCRETE
      discreteValues:
      - 0
      - 1
    - parameterName: res
      type: DISCRETE
      discreteValues:
      - 0
      - 1
    - parameterName: ps
      type: DISCRETE
      discreteValues:
      - 0
      - 1
    - parameterName: cycle_lr
      type: DISCRETE
      discreteValues:
      - 0
      - 1
    - parameterName: actv
      type: CATEGORICAL
      categoricalValues:
      - relu
      - selu
      - lrelu
    - parameterName: dr
      type: DOUBLE
      minValue: 0
      maxValue: 0.5
      scaleType: UNIT_LINEAR_SCALE
    - parameterName: l_ssim
      type: DOUBLE
      minValue: 0
      maxValue: 1
      scaleType: UNIT_LINEAR_SCALE
    - parameterName: l_mse
      type: DOUBLE
      minValue: 0
      maxValue: 1
      scaleType: UNIT_LINEAR_SCALE
    - parameterName: l_mae
      type: DOUBLE
      minValue: 0
      maxValue: 1
      scaleType: UNIT_LINEAR_SCALE
    - parameterName: lr
      type: DOUBLE
      minValue: 0.0002
      maxValue: 0.02
      scaleType: UNIT_LOG_SCALE
    - parameterName: l1
      type: DOUBLE
      minValue: 0.00001
      maxValue: 0.1
      scaleType: UNIT_LOG_SCALE
    - parameterName: l2
      type: DOUBLE
      minValue: 0.00001
      maxValue: 0.1
      scaleType: UNIT_LOG_SCALE
