trainingInput:
  scaleTier: BASIC_GPU
  runtimeVersion: '1.13'
  hyperparameters:
    goal: MAXIMIZE
    hyperparameterMetricTag: epoch_val_ssim
    maxTrials: 1000
    maxParallelTrials: 10
    enableTrialEarlyStopping: TRUE
    params:
    - parameterName: lg_c
      type: DISCRETE
      discreteValues:
      - 0
      - 1
    - parameterName: res
      type: DISCRETE
      discreteValues:
      - 0
      - 1
    - parameterName: ps
      type: DISCRETE
      discreteValues:
      - 0
      - 1
    - parameterName: actv
      type: CATEGORICAL
      categoricalValues:
      - relu
      - selu
    - parameterName: f_h
      type: INTEGER
      minValue: 3
      maxValue: 7
      scaleType: UNIT_LINEAR_SCALE
    - parameterName: f_w
      type: INTEGER
      minValue: 3
      maxValue: 7
      scaleType: UNIT_LINEAR_SCALE
    - parameterName: f1
      type: INTEGER
      minValue: 2
      maxValue: 8
      scaleType: UNIT_LINEAR_SCALE
    - parameterName: dr
      type: DOUBLE
      minValue: 0
      maxValue: 0.5
      scaleType: UNIT_LINEAR_SCALE
    - parameterName: lr
      type: DOUBLE
      minValue: 0.00001
      maxValue: 0.01
      scaleType: UNIT_LOG_SCALE
    - parameterName: l1
      type: DOUBLE
      minValue: 0
      maxValue: 0.1
      scaleType: UNIT_LOG_SCALE
    - parameterName: l2
      type: DOUBLE
      minValue: 0
      maxValue: 0.1
      scaleType: UNIT_LOG_SCALE
    - parameterName: l_ssim
      type: DOUBLE
      minValue: 0
      maxValue: 1
      scaleType: UNIT_LINEAR_SCALE
    - parameterName: l_mae
      type: DOUBLE
      minValue: 0
      maxValue: 1
      scaleType: UNIT_LINEAR_SCALE
    - parameterName: l_mse
      type: DOUBLE
      minValue: 0
      maxValue: 1
      scaleType: UNIT_LINEAR_SCALE
